- name: Set up local workstation
  hosts: local
  roles:
    - role: git
      tags:
        - git
    - role: apt
      tags:
        - apt
    - role: snap
      tags:
        - snap
    - role: zsh
      tags:
        - zsh
    - role: fzf
      tags:
        - fzf
    - role: vim
      tags:
        - vim
    - role: tmux
      tags:
        - tmux
